steps:
  # Building Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/eminent-range-419211/jenkins-cicd/image-name:tag', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/eminent-range-419211/jenkins-cicd/image-name:tag']

  # Running Docker Compose (if needed)
  - name: 'docker/compose:latest'
    args: ['up', '-d']

options:
  logging: GCS_ONLY

