version: '3'

networks:
  prodnetwork:
    external: true

volumes:
  nexus-data:
  jenkins-data:
  prom_data:

services:
  nexus:
    hostname: nexus
    domainname: nexus.local
    build:
      context: ./nexus
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - prodnetwork
    volumes:
      - nexus-data:/nexus-data
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          memory: 2G

  jenkins:
    hostname: jenkins
    domainname: jenkins.local
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - prodnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          memory: 1G

  sonardb:
    hostname: sonardb
    domainname: sonardb.local
    networks:
      - prodnetwork
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
    extra_hosts:
      - host.docker.internal:host-gateway

  sonar:
    hostname: sonar
    domainname: sonar.local
    image: sonarqube
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          memory: 2G

  gitlab:
    hostname: gitlab
    domainname: gitlab.local
    image: gitlab/gitlab-ce:latest
    restart: always
    networks:
      - prodnetwork
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "8082:8082"
      - "8443:443"
      - "822:22"
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab
    extra_hosts:
      - host.docker.internal:host-gateway

  dns:
    image: phensley/docker-dns
    hostname: dns
    domainname: dns.local
    volumes:
      - /var/run/docker.sock:/docker.sock
    networks:
      - prodnetwork
